// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwjvabcduyfwguxjyzmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3anZhYmNkdXlmd2d1eGp5em1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDc2NjQsImV4cCI6MjA4OTUyMzY2NH0.eldcGHQEajf6N0yC3LztTPGGfm8ICQkdYjVVEUi6vl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});